Lesson 3: Flowcharts and data types
S3v3Nice/jetruby-academy-practice pull request #3
Opened 2024-11-28 13:08 UTC by S3v3Nice

2024-12-06 07:30 UTC, Godus5 requested changes

2024-12-06 07:30 UTC, Godus5 commented on lesson-3-flowcharts-datatypes/pokemon_array.rb
> +  pokemon_array = []
Не рекомендуется создавать переменные с названием метода
Код отличит, где лоакльная переменная, а где вызов метода, однако над любым кодом могут работать несколько людей, а такой момент может сбить с толку

2024-12-06 07:30 UTC, Godus5 commented on lesson-3-flowcharts-datatypes/spec/pokemon_array_spec.rb
> +    expect(pokemon_array).to eq([{ name: 'Pikachu', color: 'yellow' }])
При проверки содержимого массива у Rspec есть метод match_array, который проверяет не только наличие этих значений, но и их очерёдность
В текущем случае идёт проверка массива из 1 элемента, однако в следующем случае, где есть 2 элемента в массива, лучше использовать именно match_array
expect(pokemon_array).to match_array([{ name: 'eevee', color: 'Brown' }, { name: 'BULBASAUR', color: 'green' }])
Результат не изменится, однако проверка станет более детальной, при этом при наличии ошибки в тесте match_array отобразит конкретные расхождение в ожидаемом и результирующемом массивах

2024-12-06 07:30 UTC, Godus5 commented on lesson-3-flowcharts-datatypes/word_ending_with_cs.rb
> +    word = word.strip if word
Можно сразу сделать `.strip` на принимаемую строку
`word = gets.strip`
Проверка `if word` не имеет смысла, так как в Ruby пустая строка - это тоже объект, который не является объектом класса NilClass
По сути у Тебя все условия вида `if word` будут выполняться, так как оно хоть и не является `true`, но оно и не является `false` и `nil`
![image](https://github.com/user-attachments/assets/9e0debfb-67bc-4f92-8dd2-cb64249abc0d)

2024-12-06 07:30 UTC, Godus5 commented on lesson-3-flowcharts-datatypes/word_ending_with_cs.rb
> +    next unless word && !word.include?(' ')
Конструкция с избыточной логикой

Сложно сразу понять, что здесь подразумевается
`unless` лучше использовать, когда у Тебя, например, есть одно условие, но длинное, которое тернарным оператором `?` сложно описать, и чтобы не ставить bang (восклицательные знаки перед условием), можно использовать `unless`

В остальных случаях лучше использовать уже bang

2024-12-06 09:30 UTC, S3v3Nice commented on lesson-3-flowcharts-datatypes/spec/pokemon_array_spec.rb
> +    expect(pokemon_array).to eq([{ name: 'Pikachu', color: 'yellow' }])
Хм, оказывается наоборот, `eq` заботится об очередности, а `match_array` нет)
https://medium.com/beambenefits/array-matchers-in-rspec-42b370e3983e
Но спасибо, что упомянули этот момент, об очередности до этого не задумывался

2024-12-06 09:46 UTC, Godus5 commented on lesson-3-flowcharts-datatypes/spec/pokemon_array_spec.rb
> +    expect(pokemon_array).to eq([{ name: 'Pikachu', color: 'yellow' }])
Согласен, перепутал
В итоге хотел донести идею: при проверке массива необходимо учитывать как последовательность элементов, так и их корректную наполненость
В Rspec за это отвечают 2 метода, которые Ты хорошо описал

Самым важным критерией для массива является именно наполненность, поэтому лучше использовать `match_array`

2024-12-06 10:02 UTC, S3v3Nice commented on lesson-3-flowcharts-datatypes/word_ending_with_cs.rb
> +    word = word.strip if word
Я действовал исхода из того, что `gets` может в некоторых ситуациях вернуть nil (так и не понял, в каких, наверное не в случае ввода в консоли), а `strip` нельзя вызвать у nil значения (на это мне ругался RuboCop, и что забавно, на `chomp` он не ругался)

2024-12-24 09:55 UTC, ArchmageEnderian commented
Исправил, вопросов нет, молодец! Можно мержить 👍

2024-12-24 11:02 UTC, merged